# Generated by Django 4.2 on 2024-10-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_messages_bot_response"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qualtrics_id", models.CharField(max_length=255)),
                ("message_id", models.IntegerField()),
                ("report_id", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="interactions",
            name="chatroom_exit_time",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="nicks",
            name="language_version",
            field=models.CharField(default="pl", max_length=32),
        ),
    ]
