# Generated by Django 4.2 on 2025-03-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_reports_interactions_chatroom_exit_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExitPoll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qualtrics_id", models.CharField(max_length=255)),
                ("is_yes", models.BooleanField(default=True)),
            ],
        ),
    ]
