# Generated by Django 4.2 on 2025-03-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0012_exitpoll"),
    ]

    operations = [
        migrations.AddField(
            model_name="exitpoll",
            name="vote_seconds",
            field=models.IntegerField(default=0),
        ),
    ]
