# Generated by Django 4.2 on 2025-04-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_exitpoll_vote_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="reports",
            name="message_text",
            field=models.CharField(default="DEFAULT", max_length=2550),
        ),
    ]
