# Generated by Django 4.2 on 2025-07-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0014_reports_message_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="nicks",
            name="manipulation_type",
            field=models.CharField(default="UNKNOWN", max_length=255),
        ),
    ]
