# Generated by Django 4.2 on 2025-07-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0015_nicks_manipulation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nicks",
            name="nick",
            field=models.CharField(
                default="UNKNOWN_PROBABLY_CHAT_WITHOUT_INTERACTIONS", max_length=255
            ),
        ),
    ]
