# Generated by Django 4.2 on 2026-02-15 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0016_alter_nicks_nick"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nicks",
            name="is_manipulation_positive",
        ),
    ]
