"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import yaml
import dj_database_url
from pathlib import Path
import os

# CUSTIOMIZABLE PARAMETERS

DEBUG = True
LANGUAGE_CODE = 'pl'
DATABASES_ACTIVE = True

# CUSTIOMIZABLE PARAMETERS

with open('secrets.yaml', 'r') as file:
    yaml_file = yaml.safe_load(file)
    secret_secret_key = yaml_file['SECRET_KEY']
    database_ip = yaml_file['DATABASE_IP']
    database_password = yaml_file['DATABASE_PASSWORD']

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

SECRET_KEY = secret_secret_key


ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "pages",  # new
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "django_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # new
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "django_project.wsgi.application"

SECURE_CROSS_ORIGIN_OPENER_POLICY = None

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if DATABASES_ACTIVE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'HOST': database_ip,
            'USER': 'postgres',
            'PASSWORD': database_password,
            'NAME': 'ManipulationDB',
        }
    }
else:
    DATABASES = {
        'default': dj_database_url.config(
        default='postgresql://postgres:postgres@localhost:5432/mysite',
        conn_max_age=600
    )}

# CONNECT TO DB VIA TERMINAL
# psql -h database_ip -d ManipulationDB -U postgres 
# database_password
# \c ManipulationDB
# SELECT * FROM pages_nicks;

# COPY (SELECT xmin, * FROM pages_nicks ) TO stdout WITH (FORMAT CSV, HEADER);
# COPY (SELECT * FROM pages_nicks ) TO stdout WITH (FORMAT CSV, HEADER);
# select xmin, * from pages_nicks limit(1);

# WHERE LENGTH(qualtrics_id) < 7

'''
delete from pages_angryreactions ;
delete from pages_exitpoll       ;
delete from pages_heartreactions ;
delete from pages_interactions   ;
delete from pages_likereactions  ;
delete from pages_messages       ;
delete from pages_nicks          ;
delete from pages_reports ;

'''

#GS_BUCKET_NAME="reliable-byte-428411-d8_reliable-byte-428411-d8.appspot.com"

#DATABASES = {
#    'default': dj_database_url.config(default=DATABASE_URL)
#}

#DATABASES['default']['NAME'] = 'ManipulationDB'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
#if not DEBUG:    # Tell Django to copy static assets into a path called `staticfiles` (this is specific to Render)
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# Enable the WhiteNoise storage backend, which compresses static files to reduce disk use
# and renames the files with unique names for each version to support long-term caching
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
